extends: default

ignore:
  - node_modules

rules:
  comments: disable
  comments-indentation: disable
  document-start: disable
  line-length: disable
  truthy:
    allowed-values: ['true', 'false', 'on']
