extends: default

ignore:
  - "**/vendor/**/*.yml"
  - "**/node_modules/**/*.yml"

rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  line-length: disable
  truthy:
    allowed-values: ["true", "false", "on"]
